# Generated by Django 2.1.5 on 2022-08-17 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orderupdate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderUpdate',
            new_name='OrderUpdates',
        ),
    ]
